version: '3'
services: 
  frontend:
    build:
      context: ./
      dockerfile: dockerfile
    image: rayfront:${BUILD_NUMBER}
    container_name: frontend_container
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    # networks:
    #   - ray_next_network

# networks:
#   ray_next_network:
